### ISSUE TITLE
video

### ISSUE THREAD

**Issue by mauserr** [projeto-de-algoritmos/Grafos1_CampoMinado#1]
Oi pessoal, vcs não fizeram o vídeo de 2 min explicando o projeto enquanto mostra ele rodando.

**Comment by djorkaeffalexandre** [comment]
@mauserr nosso projeto está publicado no github pages, pensamos que por isso não haveria necessidade de fazer o vídeo, você pode encontrá-lo aqui: https://projeto-de-algoritmos.github.io/Grafos1_CampoMinado.
Devemos fazer o vídeo mesmo assim?

**Comment by mauserr** [comment]
Sim, precisa ter o vídeo, até para ouvir a explicação de vcs sobre onde entra a busca em largura.

**Comment by djorkaeffalexandre** [comment]
Beleza professor, faremos ainda hoje, valeu 👍

**Comment by djorkaeffalexandre** [comment]
Fechado via #2
