### ISSUE TITLE
Executar o projeto

### ISSUE THREAD

**Issue by darmsDD** [projeto-de-algoritmos/Grafos1_CampoMinado#4]
## Descrição
É possível executar o projeto clicando no link  https://projeto-de-algoritmos.github.io/Grafos1_CampoMinado/ , mas falta a explicação de como executar o projeto caso a pessoa clone o repositório.

**Comment by djorkaeffalexandre** [comment]
Aparentemente você não leu tudo que está escrito.
Leia atentamente a seção uso do projeto e encontrará a forma de executar o mesmo.
https://github.com/projeto-de-algoritmos/Grafos1_CampoMinado#uso

**Comment by djorkaeffalexandre** [comment]
Fechado por falta de coerência.
